name: dinov2
channels:
  - defaults
  - pytorch
  - nvidia
  - xformers
  - conda-forge
dependencies:
  - python=3.9
  - pytorch::pytorch=2.0.0
  - pytorch::pytorch-cuda=11.7.0
  - pytorch::torchvision=0.15.0
  - omegaconf
  - torchmetrics=0.10.3
  - fvcore
  - iopath
  - xformers::xformers=0.0.18
  - pip
  - pip:
    - git+https://github.com/facebookincubator/submitit
    - --extra-index-url https://pypi.nvidia.com
    - cuml-cu11
    - opencv-python
    - tifffile
    - imagecodecs
    - plotly
    - certifi
    - igraph
    - leidenalg
    - scikit-learn
    - matplotlib
    - kaleido
    - rapids-singlecell
    - pylibcugraph-cu11
    - cugraph-cu11
    - scanpy
